name: DevOps Security

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read

jobs:
  gitleaks:
    name: Secret scan
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-gitleaks.yml@01e2b12e992621fecf074b8a202f66044196f3bf # v1.0.4
    secrets: inherit
