name: DevOps / Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-release-please.yml@ef5f76c297dba0d2990210a905d045c826092427 # v1.4.3
    with:
      config-file: .release-please-config.json
      manifest-file: .release-please-manifest.json
      target-branch: main
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
